### ISSUE TITLE
Server side rendering issues

### ISSUE THREAD

**Issue by hanford** [developit/preact-compat#299]
Hello! Thanks again for making such an amazing little framework. preact-compat has been a dream to work for, and I'm excited to integrate. I've just run into one little issue, that I hope isn't a blocker, because the performance gains are tremendous! 🔥

I'll add as much code as possible, if it's relevant, note that our application runs fine in the browser, where this code isn't executed. 

So we server side render everything with React. The code looks like this:

```js
function renderReact (path, preloadedProps, callback) {
  return match({ routes: routes(noop, noop), location: path }, (err, redirect, props) => {
    if (err) return callback(err)

    const html = ReactDOMServer.renderToString(
      <EazeProvider path={path} renderOnServer={serverRenderedRoutes.some((route) => matchesLocation(route, path))}>
        <RouterContext
          {...props}
          createElement={(Component, props) => <Component {...props} preloadedProps={preloadedProps} />}
        />
      </EazeProvider>
    )

    let head = Helmet.rewind()

    const doc = base
      .replace(/<div id='{0,1}app'{0,1}><\/div>/, `<div id='app'>${html}</div>`)
      .replace(/<head>(.+)<\/head>/, (_, contents) => {
        return `
          <head ${head.htmlAttributes.toString()}>
            ${head.title.toString()}
            ${head.meta.toString()}
            ${head.link.toString()}
            ${contents}
          </head>
        `
      })

    return callback(null, doc)
  })
}
```

So we're using `react-helmet`, for the <head> tags, however I don't think that's the issue. This runs fine in a node environment, and returns HTML when the function is invoked in a purely react environment (without the preact aliasing). However, when I introduced the preact & webpack aliasing, I started seeing this error:
```js
Dynamic page loading failed!  { Invariant Violation: React.Children.only expected to receive a single React element child.
    at invariant (/Users/hanford/code/maple/render/node_modules/fbjs/lib/invariant.js:44:15)
    at Object.onlyChild [as only] (/Users/hanford/code/maple/render/node_modules/react/lib/onlyChild.js:33:84)
    at Provider.render (/Users/hanford/code/maple/render/node_modules/react-redux/lib/components/Provider.js:55:28)
    at renderToString (/Users/hanford/code/maple/render/node_modules/preact-render-to-string/dist/index.js:151:18)
    at renderToString (/Users/hanford/code/maple/render/node_modules/preact-render-to-string/dist/index.js:229:15)
    at Object.renderToString (/Users/hanford/code/maple/render/node_modules/preact-render-to-string/dist/index.js:158:11)
    at /Users/hanford/code/maple/render/index.js:9167:33
    at /Users/hanford/code/maple/render/node_modules/react-router/lib/match.js:65:5
    at /Users/hanford/code/maple/render/node_modules/react-router/lib/createTransitionManager.js:118:11
    at done (/Users/hanford/code/maple/render/node_modules/react-router/lib/AsyncUtils.js:79:19)
    at /Users/hanford/code/maple/render/node_modules/react-router/lib/AsyncUtils.js:85:7
    at /Users/hanford/code/maple/render/index.js:3872:12
    at process._tickCallback (internal/process/next_tick.js:103:7) name: 'Invariant Violation', framesToPop: 1 }
```

So, investigating this stack trace, the first error points to `react/lib/onlyChild` which is this function:
```js
function onlyChild(children) {
  !ReactElement.isValidElement(children) ? process.env.NODE_ENV !== 'production' ? invariant(false, 'React.Children.only expected to receive a single React element child.') : _prodInvariant('143') : void 0;
  return children;
}
```

weirdly, the `children` in this argument are we're failing the ternary `ReactElement.isValidElement`

if it's helpful, here is the transpiled function from above

```js
function renderReact(path, preloadedProps, callback) {
  return (0, _reactRouter.match)({ routes: (0, _router.routes)(noop, noop), location: path }, function (err, redirect, props) {
    if (err) return callback(err);

    var html = _server2.default.renderToString(_react2.default.createElement(
      _provider2.default,
      { path: path, renderOnServer: _serverRenderedRoutes2.default.some(function (route) {
          return (0, _routes.matchesLocation)(route, path);
        }) },
      _react2.default.createElement(_reactRouter.RouterContext, (0, _extends3.default)({}, props, {
        createElement: function createElement(Component, props) {
          return _react2.default.createElement(Component, (0, _extends3.default)({}, props, { preloadedProps: preloadedProps }));
        }
      }))
    ));

    var head = _reactHelmet2.default.rewind();

    var doc = _index2.default.replace(/<div id='{0,1}app'{0,1}><\/div>/, '<div id=\'app\'>' + html + '</div>').replace(/<head>(.+)<\/head>/, function (_, contents) {
      return '\n          <head ' + head.htmlAttributes.toString() + '>\n            ' + head.title.toString() + '\n            ' + head.meta.toString() + '\n            ' + head.link.toString() + '\n            ' + contents + '\n          </head>\n        ';
    });

    return callback(null, doc);
  });
}
```

Oh and here is where we're tripping up in preact-render-to-string
```js
var c = new nodeName(props, context);
				c.props = props;
				c.context = context;
				if (c.componentWillMount) c.componentWillMount();
HERE -->				rendered = c.render(c.props, c.state, c.context);

				if (c.getChildContext) {
					context = assign(assign({}, context), c.getChildContext());
				}
```

```js
		for (var _i = 0; _i < len; _i++) {
			var child = children[_i];
			if (!falsey(child)) {
				var childSvgMode = nodeName === 'svg' ? true : nodeName === 'foreignObject' ? false : isSvgMode,
HERE -->				    ret = renderToString(child, context, opts, true, childSvgMode);
				if (!hasLarge && pretty && isLargeString(ret)) hasLarge = true;
				pieces.push(ret);
			}
		}
```

**Comment by hanford** [comment]
I was able to fix this issue by forking `react-redux` and modifying it to this: https://github.com/hanford/react-redux/commit/7d6a542e7b77a72949fdc78833bd32a7b9088609

**Comment by developit** [comment]
Hi there! It looks like your aliasing on the server is actually not taking effect - you can tell because there are React internals included in the stack trace you posted.  It's likely you're using Preact + Preact-compat to render your app, but the libraries you're pulling in are actually using React.

Can you give any details about how you're doing the aliasing on the server?

**Comment by mikestead** [comment]
Not sure if this will help you but...

We have this compiling on the server with webpack and had to make sure to exclude the correct modules from externals e.g.

```
// webpack.server.js
const config = {
    ...
    target: 'node',
    node: {
        __dirname: false,
        __filename: false
    },
   externals: getExternals()
   ...
}

function getExternals() {
    const excludes = [ 'react-router', 'react-redux', 'react' ];
    return fs.readdirSync('node_modules')
        .filter((x) => !~excludes.indexOf(x))
        .reduce((nodeModules, mod) => {
             nodeModules[mod] = 'commonjs ' + mod;
             return nodeModules;
         }, {});
}
```

Without the `excludes` list, webpack won't process those libs, so they don't get aliased by preact. `react` is obviously the key one here, add others as needed.

**Comment by developit** [comment]
@mikestead are you aliasing outside webpack to handle that then? interested to know how that works.

**Comment by mikestead** [comment]
Nope just aliasing in the webpack config as usual.

```
config.resolve.alias = {
    react: 'preact-compat',
    'react-dom': 'preact-compat'
}
```

Because webpack picks up the alias and is processing react imports it seems to swap out react for preact compat, just like for the client, and all seems to work fine.

**Comment by developit** [comment]
nice!

**Comment by developit** [comment]
@hanford where did we end up with this?  Definitely looked like an aliasing issue to me (the fact that `react/*` was being included at all is basically a guarantee something is amiss there).

Alternatively - you might actually just be able to alias `react-redux` to `preact-redux` - the latter is pre-aliased with a few things stripped out, it'll both reduce your bundle size and fix the children.only issue.

**Comment by bradennapier** [comment]
Yeah, cant make this work - every single module says it can not find react.  That function gives webpack 2 a bunch of errors as well

**Comment by developit** [comment]
@bradennapier If anything is saying it can't find React, that means your aliases are not being used.  Can you elaborate on how you did the aliasing?  One common mistake I see is that people alias via Webpack, but then run their code without bundling directly in Node (which doesn't know anything about Webpack aliases).

**Comment by bradennapier** [comment]
Yeah, my problem was that that was where I was looking but I had that part correct.  Just figured it out.  I had a few components being built into a vendor dll so when we moved into the client they were not aliased.

**Comment by developit** [comment]
ahhh yeah, that sounds about right. if there was something funky required to alias that DLL by all means post it here. I think we need to add some details to the aliasing section of the preact website to cover these cases.

**Comment by bradennapier** [comment]
I just removed them all together, it was only for development anyway so I am using the dll for lodash and friends only.

**Comment by developit** [comment]
Ahh, ok. I think we can probably safely say webpack DLL's are not aliasable, that's at least good to know.

**Comment by thomas-p-wilson** [comment]
Am having the same issue here, and I referred to #242 in which I found a quick solution to get `require`s working correctly. As evidenced in the following SSR stacktrace, you can see that `preact` is being substituted for `react` as expected, and yet I am encountering the same issue.

```
Invariant Violation: React.Children.only expected to receive a single React element child.
    at invariant (/usr/src/app/node_modules/fbjs/lib/invariant.js:44:15)
    at Object.onlyChild [as only] (/usr/src/app/node_modules/react/lib/onlyChild.js:33:84)
    at Provider.render (/usr/src/app/node_modules/react-redux/lib/components/Provider.js:51:28)
    at renderToString (/usr/src/app/node_modules/preact-render-to-string/src/index.js:90:18)
    at renderToString (/usr/src/app/node_modules/preact-render-to-string/src/index.js:97:11)
    at renderToString (/usr/src/app/node_modules/preact-render-to-string/src/index.js:97:11)
    at /usr/src/app/src/js/server/core/middleware/post/react-server.js:46:30
    at run (/usr/src/app/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:87:22)
    at /usr/src/app/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:100:28
    at flush (/usr/src/app/node_modules/babel-polyfill/node_modules/core-js/modules/_microtask.js:18:9)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
```

Am about to try with `preact-redux` as suggested above. Will advise on my progress.

**Comment by thomas-p-wilson** [comment]
Problem solved with `preact-redux`!

**Comment by mgutz** [comment]
Still seeing this issue. The easiest workaround is to symlink `preact-compact` to `react` and `react-dom` in node_modules.

**Comment by sedlukha** [comment]
```
"_moduleAliases": {
  "react": "node_modules/preact/compat/dist/compat.js",
  "react-dom": "node_modules/preact/compat/dist/compat.js"
}
```
solved my issue on server side (preact 10.4.0)

there was a problem with using `react-redux` on server

**Comment by developit** [comment]
Yes, for Node/SSR [module-alias](https://npm.im/module-alias) is a good solution with the configuration @sedlukha posted.

**Comment by rodynenko** [comment]
@sedlukha Can you help how to patch `preact-cli@3.0.0-rc.10` with `module-alias`? where is the place for `require('module-alias/register')`? Thanks

**Comment by sedlukha** [comment]
@rodynenko I don't use preact-cli. You need to add `require('module-alias/register')` at the very main file of server side of your app, before any code. 

 In my case I use [razzle](https://github.com/jaredpalmer/razzle) for ssr. So my target file is `server.js`.([preact example](https://github.com/jaredpalmer/razzle/blob/master/examples/with-preact/src/server.js))

**Comment by marvinhagemeister** [comment]
@rodynenko This shouldn't be needed for `preact-cli` it has the alias properties already set up in webpack.

**Comment by rodynenko** [comment]
@sedlukha @marvinhagemeister Thanks. It seems to be en error in my code.

**Comment by hanford** [comment]
Is this resolved? No longer relevant to me / happy to close if it's resolved
