### ISSUE TITLE
Issues with react-hot-loader@3.0.0-beta.6

### ISSUE THREAD

**Issue by dignifiedquire** [developit/preact-compat#337]
I am trying to alias `react` to `preact-compat` in my dev environment but running into the following issue:

<img width="1197" alt="screen shot 2017-03-29 at 11 21 14" src="https://cloud.githubusercontent.com/assets/790842/24447609/dfa3bee0-1471-11e7-9826-17fa2e362766.png">

I am using the setup from https://github.com/preact-compat/react and aliasing with webpack.

**Comment by developit** [comment]
Hi there @dignifiedquire - are you using Webpack 1, or 2?

Something is freezing the exports of `preact-compat`.

**Comment by dignifiedquire** [comment]
I am using `webpack@2.3.1`, with the following babel config

```json
"presets": [
    [
      "latest", {
        "es2015": {
          "modules": false
        }
      }
    ],
    "stage-2",
    "react"
  ],
```

**Comment by developit** [comment]
I know this isn't the most elegant solution, but can you try adding this alias?

```js
{
  alias: {
    'preact-compat': 'preact-compat/dist/preact-compat'
  }
}
```

I think it's something to do with the CommonJS proxy module re-exporting an ES Module - Webpack seems to be freezing something... somewhere (can't seem to find where).

**Comment by dignifiedquire** [comment]
This works :) thank you

**Comment by garmjs** [comment]
`webpack 2.3.2`
`react-hot-loader v3` 

Had same issue, that fixed for me too

```
{
  alias: {
    'preact-compat': 'preact-compat/dist/preact-compat'
  }
}
```

**Comment by developit** [comment]
@garmjs which version of `preact-compat` was that with?

**Comment by garmjs** [comment]
@developit sorry forget to mention its `preact-compat@3.14.3`

**Comment by garmjs** [comment]
btw just realized with this hot reload is not working

**Comment by developit** [comment]
For sure - RHL is trying to patch a frozen exports object for some reason.  Not sure what the best way to fix this would be, it's just a very odd behavior for RHL.

**Comment by garmjs** [comment]
@developit  i'm having another issue with `react-modal` too, inputs are losing focus `onChange`, i don't know yet why need to check further and open an issue if needed.

**Comment by developit** [comment]
@garmjs might be a bubbling issue. If something up the DOM tree accidentally registered an `onChange` handler on a random element like a `<div>` it'll trigger when blurring descendants.

**Comment by dignifiedquire** [comment]
So interesting enough, I have come back to trying and move my app to preact, but now I get an issue where the app is constantly rerendering if I use hot module reloading. If I remove `'react-hot-loader/patch'` from the webpack entry config it stops. Any ideas what this could be?

**Comment by developit** [comment]
Not sure, but RHL is on my list of things to figure out.  I've never used it, all the apps I work on just use basic HMR, but I know people really want it.

**Comment by levibuzolic** [comment]
This fix works except it then causes issues with using `react-dom/server`

```
ERROR in Error: Cannot find module "react-dom/server"
    at webpackMissingModule (webpack:///./html.js?:12:79)
    at Object.eval (webpack:///./html.js?:12:172)
    at eval (webpack:///./html.js?:114:30)
    at Object../html.js (index.js:2425:1)
    at __webpack_require__ (index.js:30:30)
    at index.js:73:18
    at index.js:76:10
    at webpackUniversalModuleDefinition (index.js:3:20)
    at index.js:10:3
    at ContextifyScript.Script.runInContext (vm.js:53:29)
```

**Comment by dictions** [comment]
@developit that suggestion works to fix that error, but then causes `create-react-class` alias to fail.

```
ERROR in ./src/components/Portal.jsx
Module not found: Error: Can't resolve 'create-react-class' in '/Users/ianwilliams/dev/tapwater/frontend/src/components'
 @ ./src/components/Portal.jsx 15:24-53
 @ ./src/components/DraftLink.jsx
 @ ./src/components/DraftContentInput.jsx
 @ ./src/components/DraftBody.jsx
 @ ./src/routes/Draft.jsx
 @ ./src/routes/App.jsx
 @ ./src/components/Root.jsx
 @ ./src/client.js
 @ multi webpack-dev-server/client?http://localhost:3000 webpack/hot/only-dev-server react-hot-loader/patch ./client.js

```
