### ISSUE TITLE
Incompatible with Babel 6

### ISSUE THREAD

**Issue by dmorrison42** [developit/preact-compat#34]
The following errors are thrown during build:

```
ERROR in ./~/proptypes/index.js
Module build failed: ReferenceError: [BABEL] ./~/node_modules/proptypes/index.js: Using removed Babel 5 option: ./~/node_modules/proptypes/.babelrc.loose - Specify the `loose` option for the relevant plugin you are using or use a preset that sets the option.
    at Logger.error (./~/node_modules/babel-core/lib/transformation/file/logger.js:39:11)
    at OptionManager.mergeOptions (./~/node_modules/babel-core/lib/transformation/file/options/option-manager.js:265:20)
    at OptionManager.addConfig (./~/node_modules/babel-core/lib/transformation/file/options/option-manager.js:207:10)
    at OptionManager.findConfigs (./~/node_modules/babel-core/lib/transformation/file/options/option-manager.js:413:16)
    at OptionManager.init (./~/node_modules/babel-core/lib/transformation/file/options/option-manager.js:461:12)
    at File.initOptions (./~/node_modules/babel-core/lib/transformation/file/index.js:194:75)
    at new File (./~/node_modules/babel-core/lib/transformation/file/index.js:123:22)
    at Pipeline.transform (./~/node_modules/babel-core/lib/transformation/pipeline.js:45:16)
    at transpile (./~/node_modules/babel-loader/index.js:14:22)
    at Object.module.exports (./~/node_modules/babel-loader/index.js:88:12)
 @ ./~/preact-compat/dist/preact-compat.js 6:132-152 6:243-308

ERROR in ./~/preact-svg/dist/preact-svg.js
Module build failed: ReferenceError: [BABEL] ./~/node_modules/preact-svg/dist/preact-svg.js: Using removed Babel 5 option: ./~/node_modules/preact-svg/.babelrc.modules - Use the corresponding module transform plugin in the `plugins` option. Check out http://babeljs.io/docs/plugins/#modules
    at Logger.error (./~/node_modules/babel-core/lib/transformation/file/logger.js:39:11)
    at OptionManager.mergeOptions (./~/node_modules/babel-core/lib/transformation/file/options/option-manager.js:265:20)
    at OptionManager.addConfig (./~/node_modules/babel-core/lib/transformation/file/options/option-manager.js:207:10)
    at OptionManager.findConfigs (./~/node_modules/babel-core/lib/transformation/file/options/option-manager.js:413:16)
    at OptionManager.init (./~/node_modules/babel-core/lib/transformation/file/options/option-manager.js:461:12)
    at File.initOptions (./~/node_modules/babel-core/lib/transformation/file/index.js:194:75)
    at new File (./~/node_modules/babel-core/lib/transformation/file/index.js:123:22)
    at Pipeline.transform (./~/node_modules/babel-core/lib/transformation/pipeline.js:45:16)
    at transpile (./~/node_modules/babel-loader/index.js:14:22)
    at Object.module.exports (./~/node_modules/babel-loader/index.js:88:12)
 @ ./~/preact-compat/dist/preact-compat.js 6:154-175 6:243-308
```

**Comment by developit** [comment]
This library is built with Babel 5. What is the reason you're trying to build it with Babel 6?

**Comment by dmorrison42** [comment]
We are trying to use preact and preact-compat in a project which is transpiled using Babel 6.

When we build our project with webpack it produces those error messages.

Is there something different we should be doing?

**Comment by developit** [comment]
Nope, just wanted to know the setup.
First thing you should make sure though: you need to configure `babel-loader` to not transpile modules in `node_modules`:

```
modules: {
  loaders: [
    {
      test: /\.jsx?/,
      exclude: /node_modules/,
      loader: 'babel'
  ]
}
```

(example here: https://github.com/developit/preact-www/blob/master/webpack.config.babel.js#L53-L57)

**Comment by dmorrison42** [comment]
Thank you, this fixed the build.

**Comment by developit** [comment]
Awesome! I'm always in the [preact gitter room](https://gitter.im/developit/preact) if you run into anything else, happy to help.
