### ISSUE TITLE
react-flip-move not working with preact-compat

### ISSUE THREAD

**Issue by SamRaymer** [developit/preact-compat#372]
Hi! I'm trying to use react-flip-move with my preact project, and I'm getting an error about not being able to call children.map when I add it.

```
import {h} from 'preact'
import {Component} from 'preact-compat'
import FlipMove from 'react-flip-move'

export default class Test extends Component {
  render() {
    return (
      <FlipMove
      typeName="div"
      enterAnimation="fade"
      leaveAnimation="fade"
      >
      <div key="hi"/>
      </FlipMove>
    )
  }
}
```

```
TypeError: props.children.map is not a function
    at new FlipMove (https://localhost:8000/js/***.js:2653:32)
    at createComponent (https://localhost:8000/js/vendor.js:7095:20)
    at renderComponent (https://localhost:8000/js/vendor.js:7154:55)
    at setComponentProps (https://localhost:8000/js/vendor.js:7127:103)
    at buildComponentFromVNode (https://localhost:8000/js/vendor.js:7214:13)
    at idiff (https://localhost:8000/js/vendor.js:7017:57)
...
```

Thanks!

**Comment by developit** [comment]
Hi there!  I'm actually not sure why react-flip-move is trying to use props.children.map, since that should be undefined in React as well.  However, adding an empty Text node seems to fix the issue.  Here is a JSFiddle reproduction that you can see working with the empty text node added:

https://jsfiddle.net/developit/3cqbq0n7/

**Comment by SamRaymer** [comment]
Interesting! Thanks for looking into it!
